# Generated by Django 5.0.1 on 2024-12-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QRTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_at", models.DateTimeField(blank=True, null=True)),
                ("is_suspicious", models.BooleanField(default=False)),
                ("suspicion_reason", models.TextField(blank=True)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
